### ISSUE TITLE
Module evee/es6 not found.

### ISSUE THREAD

**Issue by schuchowsky** [SplittyDev/evee.js#6]
I have just installed evee `^2.1.0` version.

The project description say:
>The evee/es6 export is the ES6 version of evee, which is generally faster.

I'm trying to import using es6: `import Evee from 'evee/es6'`. But the module doesn't seem to exist. Getting the error `Module not found: 'evee/es6'`.

It's weird because it's fairly simple. Am I missing something?

**Comment by SplittyDev** [comment]
Hey, apparently I forgot to bundle the es6 version with the published package..

I'll try to fix this as soon as I can.
For now, please just use the regular version.
It's still incredibly fast, even as many as 250,000+ events per second should run perfectly fine.

I'm very sorry.
